wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721917697
    t:
      1:
      - 1
      - 5
      - 37
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 37
      - 51
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.19
      5: 0.17.5
      8:
      - 3
      - 5
      - 9
      13: windows-amd64
_cfg_dict:
  desc: null
  value:
    common_params:
      initial_amount: 100000
      transaction_cost_pct: 0.0
      tech_indicator_list:
      - high
      - low
      - open
      - close
      - adjcp
      - zopen
      - zhigh
      - zlow
      - zadjcp
      - zclose
      - zd_5
      - zd_10
      - zd_15
      - zd_20
      - zd_25
      - zd_30
      temperature: 1
      timesteps: 5
      batch_size: 64
      num_epochs: 10
      length_day: 10
      seq_len: 20
      label_len: 5
      pred_len: 5
      model: iTransformer
      wandb_project_name: 2025_AAAI_Exp
      wandb_group_name: main_exp
      wandb_session_name: exp_num
      gpu_ids:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      lr: 1.0e-06
      norm_method: ticker
    dataset_name: dj30
    net_name: AAAI
    agent_name: AAAI
    optimizer_name: adam
    loss_name: mse
    work_dir: work_dir/dj30_AAAI_AAAI_adam_mse
    batch_size: 64
    wandb_project_name:
    - 2025_AAAI_Exp
    wandb_group_name:
    - main_exp
    wandb_session_name:
    - exp_num
    gpu_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    data:
      type: AAAI_mse_Dataset
      data_path: data/dj30
      train_path: train.csv
      valid_path: valid.csv
      test_path: test.csv
      test_dynamic_path: test_with_label.csv
      tech_indicator_list:
      - high
      - low
      - open
      - close
      - adjcp
      - zopen
      - zhigh
      - zlow
      - zadjcp
      - zclose
      - zd_5
      - zd_10
      - zd_15
      - zd_20
      - zd_25
      - zd_30
      size:
      - 20
      - 5
      - 5
      features: MS
      scale: true
      timeenc: 1
      freq: D
      length_day: 10
      timesteps: 5
      initial_amount: 100000
      transaction_cost_pct: 0.0
    environment:
      type: AAAIEnvironment
    transition:
      type: Transition
    agent:
      type: AAAI
      memory_capacity: 1000
      gamma: 0.99
      policy_update_frequency: 500
      timesteps: 5
    trainer:
      type: AAAI_mse
      pred_len: 5
      epochs: 10
      gamma: 0.05
      work_dir: work_dir/dj30_AAAI_AAAI_adam_mse
      if_remove: false
      wandb_project_name: 2025_AAAI_Exp
      wandb_group_name: main_exp
      wandb_session_name: exp_num
      temperature: 1
    loss:
      type: MSELoss
    optimizer:
      type: Adam
      lr: 1.0e-06
    act_net:
      type: AAAI_mse
      attention_bool: 'True'
      model: iTransformer
      dropout: 0.05
      num_stocks: 29
      seq_len: 20
      label_len: 5
      pred_len: 5
      modes: 64
      enc_in: 16
      dec_in: 16
      c_out: 16
      d_model: 256
      n_heads: 4
      e_layers: 2
      d_layers: 1
      output_attention: true
      embed: timeF
      freq: d
      factor: 1
      d_ff: 512
      activation: gelu
      use_norm: true
_filename:
  desc: null
  value: C:\Users\JK\PycharmProjects\2025_AAAI\configs\dj30_AAAI_mse.py
_text:
  desc: null
  value: "import os\nimport sys\nsys.path.insert(0, os.path.dirname(__file__))\nfrom\
    \ configs.common_config  import common_params\n\n\n# task_name = \"portfolio_management\"\
    \ndataset_name = \"dj30\"\nnet_name = \"AAAI\"\nagent_name = \"AAAI\"\noptimizer_name\
    \ = \"adam\"\nloss_name = \"mse\"\nwork_dir = f\"work_dir/{dataset_name}_{net_name}_{agent_name}_{optimizer_name}_{loss_name}\"\
    \n\n\nbatch_size = 64\nwandb_project_name =common_params['wandb_project_name'],\n\
    wandb_group_name =common_params['wandb_group_name'],\nwandb_session_name =common_params['wandb_session_name'],\n\
    gpu_ids = common_params['gpu_ids']\ndata = dict(\n    type='AAAI_mse_Dataset',\n\
    \    data_path='data/dj30',\n    train_path='train.csv',\n    valid_path='valid.csv',\n\
    \    test_path='test.csv',\n    test_dynamic_path='test_with_label.csv',\n   \
    \ tech_indicator_list= common_params['tech_indicator_list'],\n    size=[common_params['seq_len'],\
    \ common_params['label_len'], common_params['pred_len']],\n    features = 'MS',\n\
    \    scale = True,\n    timeenc = 1,\n    freq = 'D',\n    length_day=common_params['length_day'],\n\
    \    timesteps=common_params['timesteps'],\n    initial_amount=common_params['initial_amount'],\n\
    \    transaction_cost_pct=common_params['transaction_cost_pct'])\n\nenvironment\
    \ = dict(type='AAAIEnvironment')\n\ntransition = dict(\n    type = \"Transition\"\
    \n)\nagent = dict(\n    type='AAAI',\n    memory_capacity=1000,\n    gamma=0.99,\n\
    \    policy_update_frequency=500,timesteps=5)\n\ntrainer = dict(\n    type='AAAI_mse',\n\
    \    pred_len = common_params['pred_len'],\n    epochs=common_params['num_epochs'],\n\
    \    gamma = 0.05,\n    work_dir=work_dir,\n    if_remove=False,\n    wandb_project_name\
    \ =common_params['wandb_project_name'],\n    wandb_group_name =common_params['wandb_group_name'],\n\
    \    wandb_session_name =common_params['wandb_session_name'],\n    temperature\
    \ = common_params['temperature'])\n\nloss = dict(type='MSELoss')\noptimizer =\
    \ dict(type='Adam', lr=common_params['lr'])\n\nact_net = dict(\n    type='AAAI_mse',\n\
    \    attention_bool='True',\n    model = common_params['model'],\n    dropout\
    \ = 0.05,\n    num_stocks = 29,\n    seq_len = common_params['seq_len'],\n   \
    \ label_len = common_params['label_len'],\n    pred_len = common_params['pred_len'],\n\
    \    modes = 64,\n    enc_in = 16,\n    dec_in = 16,\n    c_out = 16,\n    d_model\
    \ = 256,\n    n_heads = 4,\n    e_layers = 2,\n    d_layers = 1,\n    output_attention\
    \ = True,\n    embed= 'timeF',\n    freq = 'd',\n    factor = 1,\n    d_ff = 512,\n\
    \    activation = 'gelu',\n    use_norm = True)\n\n\n\n\n\n\n\n\n"
